# Generated by Django 2.1.4 on 2019-02-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(max_length=20)),
                ('face_key', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=30)),
            ],
        ),
    ]
