# Generated by Django 2.1.4 on 2019-02-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='face_image',
            field=models.FileField(default=1, upload_to='', verbose_name='/face_image'),
            preserve_default=False,
        ),
    ]
