# Generated by Django 2.1.4 on 2019-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccount_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='face_image',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='person_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
