# Generated by Django 2.1.4 on 2019-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190216_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='person_id',
            field=models.CharField(max_length=60),
        ),
    ]
